name: Calling - Create APIM Instance
on:
  workflow_dispatch:

jobs:
  create_api:
    uses: gmansoain/example-reusable-workflows/.github/workflows/template_create_apim_instance.yml@main
    with:
      ASSET_ID: slack-system-id
      ASSET_VERSION: 1.0.1
      MULE_ORG_ID: ${{ secrets.MULE_ORG_ID }}
      MULE_USERNAME: ${{ secrets.MULE_USERNAME }}
      MULE_PASSWORD: ${{ secrets.MULE_PASSWORD }}
      MULE_BG_ID: fc9e3283-a489-4e88-99aa-cceea4aa5ea1
      ENVIRONMENT: Development
