name: Calling - Create APIM Instance
on:
  workflow_dispatch:

jobs:
  create_api:
    uses: gmansoain/example-reusable-workflows/.github/workflows/template_create_apim_instance.yml@main
    with:
      ASSET_ID: slack-system-api
      ASSET_VERSION: 1.0.1
      ENVIRONMENT: Development
    vars:
      MULE_BG_ID: ${{ vars.MULE_BG_ID }}
    secrets:
      MULE_USERNAME: ${{ secrets.MULE_USERNAME }}       
      MULE_PASSWORD : ${{ secrets.MULE_PASSWORD }}
      MULE_ORG_ID: ${{ secrets.MULE_ORG_ID}}
