name: Reusable Workflow with Parameters

on:
  workflow_call:
    inputs:
      gon_param_1:
        required: false
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Print parameter
      run: echo 'Gon Parameter value:'

 
