name: Reusable - Create APIM instance

on:
  workflow_call:
    inputs:
      ASSET_ID:
        type: string
        required: true
      ASSET_VERSION:
        type: string
        required: true
      MULE_ORG_ID:
        type: string
        required: true
      MULE_USERNAME:
        type: string
        required: true
      MULE_PASSWORD:
        type: string
        required: true
      MULE_BG_ID:
        type: string
        required: true
      ENVIRONMENT:
        type: string
        required: true


jobs:
  create_apim_instance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Install Node on the runner
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install anypoint-cli
      run: |
        npm install -g anypoint-cli-v4
    - name: check version
      run: |
        anypoint-cli-v4 --version
    - name: Set Authentication
      env:
        MULE_USERNAME: ${{ inputs.MULE_USERNAME }}
        MULE_PASSWORD: ${{ inputs.MULE_PASSWORD }}
        MULE_ORG_ID: ${{ inputs.MULE_ORG_ID }}
      run: |
        anypoint-cli-v4 conf username $MULE_USERNAME
        anypoint-cli-v4 conf password $MULE_PASSWORD
        anypoint-cli-v4 conf organization $MULE_ORG_ID
    - name: Create APIM instance
      env:
        ASSET_ID: ${{ inputs.ASSET_ID }}
        ASSET_VERSION: ${{ inputs.ASSET_VERSION }}
        MULE_BG_ID: ${{ inputs.MULE_BG_ID }}
        ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      run: |
          anypoint-cli-v4 api-mgr:api:manage -m --deploymentType=cloudhub --organization $MULE_BG_ID --environment $ENVIRONMENT $ASSET_ID $ASSET_VERSION | sed -e "s/Created new API with ID: //g" > ./api_id.txt
    - name: Create variable in repo
      env:
        GITHUB_TOKEN: ${{ secrets.GON_GITHUB_TOKEN }}
      run: |
        gh variable set API_ID --body "$(cat ./api_id.txt)"
